#!/bin/sh

sudo cp -r ../livescore-cli ~/.livescore-cli
sudo ln -sf ~/.livescore-cli/livescore.py /usr/local/bin/livescore

sudo sed -i '' '18i\
    #' ~/.livescore-cli/lib/lsprint.py

sudo sed -i '' '21i\
    #' ~/.livescore-cli/lib/lsprint.py

if sudo pip2 install bs4 requests; then
    osascript -e 'display notification "Setup Completed" with title "livescore-cli"'
else
    echo "failed to install bs4 and requests python package"
fi
